### ISSUE TITLE
Maximum Cut replication.

### ISSUE THREAD

**Issue by utkuumur** [ml-jku/DIffUCO#1]
Hello,

Thank you for making the codes public! I'm interested in applying your approach to the Maximum Cut problem. However, I couldn't find any examples or documentation related to Maximum Cut tasks in the repository.

I have a custom dataset for Maximum Cut and would love to test your models on it. Would it be possible to share any pointers or parameters used for training models on Maximum Cut datasets? Even if there aren't specific examples, any guidance would be greatly appreciated.

Thank you!

**Comment by sanokows** [comment]
Hello,

Yes, the Maximum Cut Problem is implemented and you should be able to apply
our method to it.

How you can do it:
First, create the dataset e.g.:

cd /DatasetCreator
python prepare_datasets.py --dataset BA_small--problem MaxCut
--time_limits 2. 0.1 1.

if you have your own dataset you will have to implement your own class
in DIffUCO/DatasetCreator/loadGraphDatasets/.

Finally, after you have created your dataset you can run experiments by
specifying the dataset with --IsingMode and the EnergyDunction with
--EnergyFunction.

On the example of the BA_small dataset, this would look like that:

python argparse_ray_main.py --lrs 0.002 --GPUs 0 --n_GNN_layers 8
--temps 0.6 --IsingMode BA_small --EnergyFunction MaxCut --N_anneal
2000
--n_diffusion_steps 3 --batch_size 20 --n_basis_states 10
--noise_potential bernoulli --project_name FirstRuns --seed 123


Please let me know if you encounter any problems.

Best,

Sebastian Sanokowski

**Comment by utkuumur** [comment]
Thank you so much for the swift answer. I managed to make it work. Should I use the last value of the eval/best_MaxCut_Value on Wandb as the reported objective function value?

**Comment by sanokows** [comment]
eval/best_MaxCut_Value is the best MaxCut value on the validation set out of "n_basis_states" that you chose as a hyperparameter.
The best network is always chosen according to the best achieved eval/mean_energy during training.

What do you mean as "objective function value"? Do you mean the function according to which you want to optimize hyperparameters?
If yes, I would recommend to use "eval/best_energy", which is the average_energy obtained by the best checkpoint on the validation set.

FYI: I will be on vacation until the 2. July, so unfortunately I will not respond until that day. However, feel free to ask further questions if something is unclear.

**Comment by utkuumur** [comment]
I hope you had a relaxing vacation. I’m currently working on replicating the MIS, MaxCut, and MClique tasks and using the `ConditionalExpectation.py` file to evaluate the models after training. I have a few questions I was hoping you could clarify:

- In the paper, you report sizes for each task. Which value produced by `ConditionalExpectation.py` corresponds to these sizes? Is it `test/mean_best_energy_CE?` If so, does this value correspond to the independent set size for MIS, the clique size for MClique, and the number of cut edges for MaxCut? Additionally, are these reported sizes based on the hard solutions rather than the soft ones? I assume the CE models handle this through the conditional expectation approach, but does this also apply to the vanilla model?

- Regarding the reported times, which value corresponds to the timing results? Would it be the `test/overall_time` value?

- Lastly, could you guide me on how to produce the results for the vanilla, CE, and CE-ST_8 models?

Thanks so much for your help! I look forward to your response.

**Comment by sanokows** [comment]
`In the paper, you report sizes for each task. Which value produced by ConditionalExpectation.py corresponds to these sizes? Is it test/mean_best_energy_CE?`
It depends on the setting. In Table 1 and Table 3 we report the average solution sizes. Therefore, DiffUCO-CE is reported with "test/mean_energy_CE". In Fig. 2 left the best solution size out of eight states is reported. Therefore, if you set in "ConditionalExpectation.py" the correct amount of "--n_samples 8" the metric "test/mean_best_energy_CE" will give you the corresponding size from Fig 2. For the vanilla version you would report "test/mean_energy" or "test/mean_best_energy" accordingly.
(Note that in some cases like MIS the Energy is defined as the negative of the set size.)

`If so, does this value correspond to the independent set size for MIS, the clique size for MClique, and the number of cut edges for MaxCut?`
On all problems except MaxCut this then corresponds to the solution value (modulo the minus sign in some cases). On MaxCut you have to read out "test/MaxCut_Value_CE" for the average value of DiffUCO-CE "test/best_MaxCut_Value_CE" for the best out of X solutions of DiffUCO-CE.

`Additionally, are these reported sizes based on the hard solutions rather than the soft ones?
I assume the CE models handle this through the conditional expectation approach, but does this also apply to the vanilla model?`
How do you define soft solutions? Do you mean the average energy value computed with exact expectation?
In the vanilla case solutions are always computed via retrieving samples from the model and as you said with CE samples are generated with the application of CE.

`Regarding the reported times, which value corresponds to the timing results? Would it be the test/overall_time value?`
Yes "test/overall_time" gives you the time for CE + generation time. However, you have to be careful, because jax functions are first compiled via jit compilation which can take a lot of time. As you do not want to measure the compilation time you should measure time with the "--measure_time True" flag in ConditionalExpectation.py. Here, all functions are pre-compiled which can take some time and then the generation procedure is measured. Also please read App. C.7 of the paper for more details on time measurement.

Edit: I just noticed that "test/overall_time" will not give you the overall runtime, but the runtime per graph.

`Lastly, could you guide me on how to produce the results for the vanilla, CE, and CE-ST_8 models?`
For vanilla and CE you read off the solution sizes as explained above.
Unfortunately, CE-ST is currently not implemented in the codebase because I have restructured some parts of the code.
Also, I have reimplemented the CE from a CPU based implementation to a faster GPU based implementation and I did not have the time yet to implement a GPU based CE-ST.

**Comment by utkuumur** [comment]
Thank you for the response! It made it clear on most ends. I meant that the solutions are 0/1 versus 0.99, 0.0001 etc by hard/soft solutions.

I have successfully run the models on small datasets and even on a large dataset around 1k nodes on max cut. However, I get memory errors for the maximum independent set and maximum clique. 

Specifically, I am trying to train the model via `--lrs 0.002 --GPUs 0 --n_GNN_layers 7 --temps 0.3 --IsingMode RB_iid_large --EnergyFunction MIS --N_anneal 3000 --n_diffusion_steps 4 --batch_size 18 --n_basis_states 10 --noise_potential Bernoulli --project_name FirstRuns --seed 123 --stop_epochs 200` for RB graphs with nodes 800 to 1200. 

However, after the first epoch, I get the following error.
`
ValueError: RESOURCE_EXHAUSTED: CUDA driver ran out of memory trying to instantiate CUDA graph with 9 nodes and 0 conditionals (total of 0 alive CUDA graphs in the process). You can try to (a) Give more memory to CUDA driver by reducing XLA_PYTHON_CLIENT_MEM_FRACTION (b) Disable CUDA graph with 'XLA_FLAGS=--xla_gpu_enable_command_buffer=' (empty set). Original error: Failed to instantiate CUDA graph:CUDA_ERROR_OUT_OF_MEMORY: out of memory: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).`

I tried to use 2 GPUs and reduce the batch size but those did not help. I also tried to train the model for MIS and ER graphs with p=0.15, but still had the same issue. These graphs have a smaller number of nodes but are denser in terms of edges. Do you have any idea what can cause this?

Edit: Also I allocate 40 CPU cores and 512 Gb RAM for each job. GPUs are A100 80Gb.

**Comment by utkuumur** [comment]
Actually, I am sorry it fails after an epoch for ER graphs with n ranging between 700 800, and p=0.15. For RB graphs with num nodes 800-1200, it goes up to 15 epochs with 2GPUs and a batch size of 10.

**Comment by sanokows** [comment]
Can you try to rerun your experiments with `--mem_frac 0.8` or `--mem_frac 0.7`. 
If you do so does this problem still happen?

By setting `--mem_frac 0.8` you allocate 80% of the GPU memory for your training and the other 20% can be used for storing jit compiled methods.
With GNNs the train method is jit compiled quite often and if this is done too often this can exceed the available rest memory.

Please let me know if this solves your issue.

**Comment by utkuumur** [comment]
Thank you for taking the time to help me! I really appreciate it. I tried those but they did not work. I freshly installed everything again and tried to block preallocation and see the memory usage. The memory usage is quite high. I can train the model for the ER dataset (with 700-800 graphs) using 4 A100 80GB and batch size of 16 (4 each). I can work with this! Thank you so much for the help.

**Comment by sanokows** [comment]
Just so that you have a reference:
For RB_iid_large on MIS with `--n_diffusion_steps 6 --batch_size 40 --n_basis_states 2` I run experiments on 4 A100 GPUs with 40 GB memory.
In the case of ER graphs, I agree with you that the connectivity of these graphs is very high and I think that is the reason why you need so much memory.

In my latest code, I have added a smarter way of padding graphs which should lead to better memory efficiency.
If you are interested I could push this code to another branch of the repo.
